### ISSUE TITLE
🐛 Relative import are not suported for cogs loading

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#127]
```py
        for cog_class in start_config:
            self.load_cog(f".cogs.{flatten_name(cog_class)}")
```

```py
Traceback (most recent call last):
  File "D:\Pincer-Bot\run.py", line 12, in <module>
    main()
  File "D:\Pincer-Bot\run.py", line 8, in main
    Bot().run()
  File "D:\Pincer-Bot\app\bot.py", line 16, in __init__
    self.load_cogs()
  File "D:\Pincer-Bot\app\bot.py", line 25, in load_cogs
    self.load_cog(f".cogs.{flatten_name(cog_class)}")
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 323, in load_cog
    module = import_module(path)
  File "C:\Users\Sigmanificient\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.cogs.info'

Process finished with exit code 1
``

**Comment by Sigmanificient** [comment]
Fixed in [f3584d7](https://github.com/Pincer-org/Pincer/tree/f3584d7ca1319539af9067a756e220eb80c9474f)
