### ISSUE TITLE
🐛 Command wont work with package based cog.

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#128]
> Bot structure
```cs
- app
    - cogs
        - __init__.py
        - info.py

    - __init__.py
    - bot.py
- run.py
```

```
DEBUG:pincer.core:New event received, checking if handler exists for opcode: 0
DEBUG:pincer.core:Event handler found, ensuring async future in current loop.
DEBUG:pincer.core:Waiting for new event.
DEBUG:pincer:`ready` middleware has been invoked
DEBUG:root:0 commands registered.
DEBUG:pincer.core:GET applications/881583379504582727/commands | null
DEBUG:pincer:`payload` middleware has been invoked
DEBUG:pincer.core:Received response for applications/881583379504582727/commands | []
DEBUG:pincer.core:Request has been sent successfully. Returning json response.
ERROR:asyncio:Task exception was never retrieved
[crash]
```

```py
future: <Task finished name='Task-9' coro=<Client.event_handler() done, defined at D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py:514> exception=KeyError('app.bot')>
Traceback (most recent call last):
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 527, in event_handler
    await self.process_event(payload.event_name.lower(), payload)
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 512, in process_event
    await self.execute_error(e)
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 490, in execute_error
    raise error
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 509, in process_event
    self.execute_event(call, *args, **kwargs)
  File "D:\Pincer-Bot\venv\lib\site-packages\pincer\client.py", line 400, in execute_event
    args = (ChatCommandHandler.managers[call.__module__], *args)
KeyError: 'app.bot'
```

**Comment by Arthurdw** [comment]
No manager seems to be registered for the `app.bot` file. This is unexpected behavior, could you share the project files? *(If you don't want it publicly, send me in a discord dm please)*

**Comment by Sigmanificient** [comment]
Here is the simplest structure that cause the issue:

```js
- app
  - __init__.py
  - bot.py
- run.py
```

> `bot.py` 
```py
from pincer import Client
from pincer.client import event


class Bot(Client):

    def __init__(self, *args, **kwargs):
        super(Bot, self).__init__(*args, **kwargs)

    @Client.event
    async def on_ready(self):
        print("hello, world")
```

`__init__.py`
```py
from .bot import Bot

__all__ = ('Bot',)
```

> `run.py`
```py
import app
import dotenv

if __name__ == '__main__':
    app.Bot(dotenv.dotenv_values('.env').get('TOKEN')).run()

```
