### ISSUE TITLE
can't launch the bot in the new version

### ISSUE THREAD

**Issue by drawbu** [Pincer-org/Pincer#224]
**Describe the bug**
Whenever I try to launch a bot (I tried multiple tokens), I get this error:
```py
F:\python\Pincer\venv\Scripts\python.exe F:/python/Pincer/examples/tweet_generator.py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Client.event_handler() done, defined at F:\python\Pincer\pincer\client.py:550> exception=TypeError("Forward references must evaluate to types. Got (<class 'str'>, <class 'int'>, <class 'float'>).")>
Traceback (most recent call last):
  File "F:\python\Pincer\pincer\client.py", line 565, in event_handler
    await self.process_event(payload.event_name.lower(), payload)
  File "F:\python\Pincer\pincer\client.py", line 548, in process_event
    await self.execute_error(e)
  File "F:\python\Pincer\pincer\client.py", line 524, in execute_error
    raise error
  File "F:\python\Pincer\pincer\client.py", line 542, in process_event
    key, args, kwargs = await self.handle_middleware(payload, name)
  File "F:\python\Pincer\pincer\client.py", line 476, in handle_middleware
    extractable = await ware(self, payload, *args, **kwargs)
  File "F:\python\Pincer\pincer\client.py", line 113, in wrapper
    return await (
  File "F:\python\Pincer\pincer\middleware\ready.py", line 53, in on_ready_middleware
    await ChatCommandHandler(self).initialize()
  File "F:\python\Pincer\pincer\commands.py", line 659, in initialize
    await self.__init_existing_commands()
  File "F:\python\Pincer\pincer\commands.py", line 517, in __init_existing_commands
    self._api_commands = await self.get_commands()
  File "F:\python\Pincer\pincer\commands.py", line 378, in get_commands
    return list(map(
  File "F:\python\Pincer\pincer\utils\api_object.py", line 236, in from_dict
    return cls(**dict(map(
  File "<string>", line 16, in __init__
  File "F:\python\Pincer\pincer\objects\app\command.py", line 158, in __post_init__
    self.options = convert(
  File "F:\python\Pincer\pincer\utils\conversion.py", line 53, in convert
    return MISSING if value is MISSING else handle_factory()
  File "F:\python\Pincer\pincer\utils\conversion.py", line 48, in handle_factory
    list(map(fin_fac, value))
  File "F:\python\Pincer\pincer\utils\conversion.py", line 45, in fin_fac
    return factory(v)
  File "F:\python\Pincer\pincer\utils\api_object.py", line 236, in from_dict
    return cls(**dict(map(
  File "<string>", line 11, in __init__
  File "F:\python\Pincer\pincer\objects\app\command.py", line 91, in __post_init__
    self.choices = convert(
  File "F:\python\Pincer\pincer\utils\conversion.py", line 53, in convert
    return MISSING if value is MISSING else handle_factory()
  File "F:\python\Pincer\pincer\utils\conversion.py", line 48, in handle_factory
    list(map(fin_fac, value))
  File "F:\python\Pincer\pincer\utils\conversion.py", line 45, in fin_fac
    return factory(v)
  File "F:\python\Pincer\pincer\utils\api_object.py", line 236, in from_dict
    return cls(**dict(map(
  File "<string>", line 7, in __init__
  File "F:\python\Pincer\pincer\utils\api_object.py", line 179, in __post_init__
    attributes = get_type_hints(self, globalns=TypeCache.cache).items()
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python38\lib\typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python38\lib\typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python38\lib\typing.py", line 517, in _evaluate
    self.__forward_value__ = _type_check(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python38\lib\typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Forward references must evaluate to types. Got (<class 'str'>, <class 'int'>, <class 'float'>).
```

I can get you some more info fetch with the logging module:
```py
import logging
logging.basicConfig(level=logging.DEBUG)
```
```log
DEBUG:pincer.core:GET applications/690602792439644181/guilds/690604075775164437/commands | None
DEBUG:pincer.core:Received response for applications/690602792439644181/guilds/690604075775164437/commands | [{"id": "851917311279104051", "application_id": "690602792439644181", "version": "851919140079140876", "default_permission": true, "default_member_permissions": null, "type": 1, "name": "new_channel", "description": "Cr\u00e9\u00e9 un nouveau salon de discussion", "guild_id": "690604075775164437", "options": [{"type": 3, "name": "name", "description": "Le nom du nouveau salon", "required": true}]}, {"id": "853188229108334652", "application_id": "690602792439644181", "version": "853188229108334655", "default_permission": true, "default_member_permissions": null, "type": 1, "name": "guild_settings", "description": "R\u00e9glages administrateur pour le serveur Discord", "guild_id": "690604075775164437", "options": [{"type": 3, "name": "option", "description": "Faites votre choix parmis les commandes disponibles", "required": true, "choices": [{"name": "Salon de bienvenue", "value": "welcome_channel"}]}]}, {"id": "864152221670178866", "application_id": "690602792439644181", "version": "864152514163900478", "default_permission": true, "default_member_permissions": null, "type": 1, "name": "test", "description": "Cr\u00e9\u00e9 un nouveau salon de discussion", "guild_id": "690604075775164437", "options": [{"type": 5, "name": "name", "description": "Le nom du nouveau salon"}]}]
DEBUG:pincer.core:Request has been sent successfully. Returning json response.
DEBUG:pincer.core:GET applications/690602792439644181/commands | None
DEBUG:pincer.core:Received response for applications/690602792439644181/commands | []
DEBUG:pincer.core:Request has been sent successfully. Returning json response.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Client.event_handler() done, defined at /home/sigmanificient/PycharmProjects/Pincer/pincer/client.py:550> exception=TypeError("Forward references must evaluate to types. Got (<class 'str'>, <class 'int'>, <class 'float'>).")>
```

**To Reproduce**
My code to reproduce the behavior:

```py
import io
import textwrap
import urllib.request
from datetime import datetime
from PIL import Image, ImageFont, ImageDraw, ImageOps
from pincer import command, Client, Descripted
from pincer.objects import Message, Embed, MessageContext


class Bot(Client):

    @Client.event
    async def on_ready(self):
        print(
            f"Started client on {self.bot}\n"
            "Registered commands: " + ", ".join(self.chat_commands)
        )

    @command(
        name='twitter',
        description='to create fake tweets',
        guild=690604075775164437
    )
    async def twitter(self, ctx: MessageContext, content: Descripted[str, '...']):
        await ctx.interaction.ack()

        message = content

        if len(message) > 280:
            return 'A tweet can be at maximum 280 characters long'

        # wrap the message to be multi-line
        message = textwrap.wrap(message, 38)

        # download the profile picture and convert it into Image object
        request = urllib.request.Request(
            f"https://cdn.discordapp.com/avatars/{ctx.author.user.id}/{ctx.author.user.avatar}.webp?size=128",
            headers={
                'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'}
        )
        avatar = urllib.request.urlopen(request).read()
        avatar = io.BytesIO(avatar)
        avatar = Image.open(avatar).convert("RGBA").resize((128, 128))

        # modify profile picture to be circular
        mask = Image.new('L', (128, 128), 0)
        draw = ImageDraw.Draw(mask)
        draw.ellipse((0, 0) + (128, 128), fill=255)
        avatar = ImageOps.fit(avatar, mask.size, centering=(0.5, 0.5))
        avatar.putalpha(mask)

        # create the tweet by pasting the profile picture into a white image
        tweet = trans_paste(
            avatar,

            # background
            Image.new('RGBA', (800, 250 + 50 * len(message)), (255, 255, 255)),

            box=(15, 15)
        )

        # add the fonts
        font = ImageFont.truetype('Segoe UI.ttf', 40)
        font_small = ImageFont.truetype('Segoe UI.ttf', 30)
        font_bold = ImageFont.truetype('Segoe UI Bold.ttf', 40)

        # write the name and username on the Image
        draw = ImageDraw.Draw(tweet)
        draw.text((180, 20), str(ctx.author.user), fill=(0, 0, 0),
                  font=font_bold)
        draw.text((180, 70), '@' + ctx.author.user.username, fill=(120, 120, 120),
                  font=font)

        # write the content of the tweet on the Image
        message = '\n'.join(message).split(' ')
        result = []

        # generate a dict to set were the text need to be in different color.
        # for example, if a word starts with '@' it will be write in blue.
        # example:
        #   [
        #       {'color': (0, 0, 0), 'text': 'hello world '},
        #       {'color': (0, 154, 234), 'text': '@drawbu'}
        #   ]
        for word in message:
            for i_o, o in enumerate(word.split('\n')):

                o += '\n' if i_o != len(word.split('\n')) - 1 else ' '

                if not result:
                    result.append({'color': (0, 0, 0), 'text': o})
                    continue

                if not o.startswith('@'):
                    if result[-1:][0]['color'] == (0, 0, 0):
                        result[-1:][0]['text'] += o
                        continue

                    result.append({'color': (0, 0, 0), 'text': o})
                    continue

                result.append({'color': (0, 154, 234), 'text': o})

        # write the text
        draw = ImageDraw.Draw(tweet)
        x = 30
        y = 170
        for o in result:
            y -= font.getsize(' ')[1]
            for l_index, line in enumerate(o['text'].split('\n')):
                if l_index != 0:
                    x = 30
                y += font.getsize(' ')[1]
                draw.text((x, y), line, fill=o['color'], font=font)
                x += font.getsize(line)[0]

        # write the footer
        draw.text(
            (30, tweet.size[1] - 60),
            datetime.now().strftime(
                '%I:%M %p · %d %b. %Y · Twitter for Discord'),
            fill=(120, 120, 120),
            font=font_small)

        return Message(
            embeds=[
                Embed(
                    title='Twitter for Discord',
                    description=''
                ).set_image(url="attachment://image0.png")
            ],
            attachments=[tweet]
        )


# https://stackoverflow.com/a/53663233/15485584
def trans_paste(fg_img, bg_img, alpha=1.0, box=(0, 0)):
    """
    paste an image into one another
    """
    fg_img_trans = Image.new("RGBA", fg_img.size)
    fg_img_trans = Image.blend(fg_img_trans, fg_img, alpha)
    bg_img.paste(fg_img_trans, box, fg_img_trans)
    return bg_img


if __name__ == "__main__":
    # Of course we have to run our client, you can replace the
    # XXXYOURBOTTOKENHEREXXX with your token, or dynamically get it
    # through a dotenv/env.
    Bot("XXXYOURBOTTOKENHEREXXX").run()
```

**Expected behavior**
I just wanted to launch a bot that provides a `slash` command `twitter` that make fake tweets from a message with Pillow and upload them as an embed:

An example of what I expected to happened, (it worked before, in 0.10):
![image](https://user-images.githubusercontent.com/69208565/142043212-540037da-a066-4dbd-8ca8-e3acb586583c.png)

**Comment by drawbu** [comment]
solved: https://github.com/Pincer-org/Pincer/releases/tag/0.11.2
