### ISSUE TITLE
🐛 Functional bots are broken?

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#262]
```py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Client.event_handler() done, defined at /home/sigmanificient/PycharmProjects/Pincer/pincer/client.py:559> exception=KeyError('__main__')>
Traceback (most recent call last):
  File "/home/sigmanificient/PycharmProjects/Pincer/pincer/client.py", line 574, in event_handler
    await self.process_event(payload.event_name.lower(), payload)
  File "/home/sigmanificient/PycharmProjects/Pincer/pincer/client.py", line 557, in process_event
    await self.execute_error(e)
  File "/home/sigmanificient/PycharmProjects/Pincer/pincer/client.py", line 531, in execute_error
    raise error
  File "/home/sigmanificient/PycharmProjects/Pincer/pincer/client.py", line 554, in process_event
    self.execute_event(calls, *args, **kwargs)
  File "/home/sigmanificient/PycharmProjects/Pincer/pincer/client.py", line 432, in execute_event
    ChatCommandHandler.managers[call.__module__],
KeyError: '__main__'
```

**Comment by Lunarmagpie** [comment]
can be fixed at the same time as #256 probably

**Comment by Arthurdw** [comment]
Is this bug still present?

**Comment by Arthurdw** [comment]
As the feature is currently working, and using this with cogs is not intended. I'll close this issue.

For future reference, if you're experiencing difficulties. Please create a new issue for your problem. _(if no other similar issue is present)_
