### ISSUE TITLE
Support for `Optional[...]` in `CommandArg`

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#302]
trying to use
`CommandArg[Optional[str], Description["..."]] = None`
raises
```py
Traceback (most recent call last):
  File "/home/sigmanificient/PycharmProjects/Pincers/Pincer/dev/context.py", line 8, in <module>
    class Bot(Client):
  File "/home/sigmanificient/PycharmProjects/Pincers/Pincer/dev/context.py", line 10, in Bot
    async def a_command(
  File "/home/sigmanificient/PycharmProjects/Pincers/Pincer/pincer/commands/commands.py", line 237, in command
    command_type = _options_type_link[annotation.command_type]
KeyError: typing.Union[str, **NoneType]
```

the "working" way to do it is the following:
```py
    async def a_command(
        self,
        ctx: MessageContext,
        content: CommandArg[str, Description["..."]] = None,
    ) -> Embed:
```
But this doesnt seems really fine as `None` doesn't seems to be typed.
The first argument should be `Optional[str]`

**Comment by ooliver1** [comment]
#480 the `fixes` part (of course) did not link and close this issue properly.
