### ISSUE TITLE
:bug: `message.channel.send` is broken within `on_message`

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#353]
### Describe the bug

`message.channel.send` is broken within `on_message`

### Steps to Reproduce

```py
@Client.event
    async def on_message(self, message: UserMessage):
        await message.channel.send("Hello world")
```

### Relevant console output

```py
Traceback (most recent call last):
  File "/home/sigmanificient/dev/pincer/bot/pincer_bot/cogs/info.py", line 125, in on_message
    await message.channel.send(Embed(description=f"[{content}]({url})"))
  File "/home/sigmanificient/dev/pincer/bot/venv/lib/python3.10/site-packages/pincer/utils/api_object.py", line 323, in channel
    return self._client.channels[self.channel_id]
KeyError: 881534044431609886
```

### Pincer Version used

`0.15.1`

**Comment by Endercheif** [comment]
This will be fixed when I finish implementing caching

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
