### ISSUE TITLE
:bug: Using enum.Enum for Flags

### ISSUE THREAD

**Issue by CircuitSacul** [Pincer-org/Pincer#400]
### Is your feature request related to a problem? Please describe.

I've noticed places in the code where flags are being treated as Enums. Shouldn't they be enum.IntFlag? A quick comparison:

```py
>>> from enum import IntEnum, IntFlag
>>> class FlagsE(IntEnum):
...     BANNED = 1 << 0
...     IS_PRO = 1 << 1
...     TEMP_BANNED = 1 << 2
...
>>> class FlagsF(IntFlag):
...     BANNED = 1 << 0
...     IS_PRO = 1 << 1
...     TEMP_BANNED = 1 << 2
...
>>> FlagsE.BANNED
<FlagsE.BANNED: 1>
>>> FlagsE.BANNED | FlagsE.IS_PRO
3
>>> FlagsE(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/tstarboard/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/opt/anaconda3/envs/tstarboard/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 3 is not a valid FlagsE
>>> # ^^^^^^^
>>> FlagsF.BANNED
<FlagsF.BANNED: 1>
>>> FlagsF.IS_PRO
<FlagsF.IS_PRO: 2>
>>> FlagsF.BANNED | FlagsF.IS_PRO
<FlagsF.IS_PRO|BANNED: 3>
>>> # notice that it's still a flags object
>>> FlagsF(3)
<FlagsF.IS_PRO|BANNED: 3>
>>> # and you can pass 3 to get the combination of flags
```

### Describe the solution you would like

Use IntFlag instead if IntEnum for things like Intents, UserFlags, etc. Where there can be multiple of each value.

### Describe alternatives you have considered

Live with it?

**Comment by Endercheif** [comment]
Fixed in [f98d6b64](https://github.com/Pincer-org/Pincer/commit/f98d6b645515f429dd34c07d109edec65cae0f70)
