### ISSUE TITLE
Circular Import Bug

### ISSUE THREAD

**Issue by Endercheif** [Pincer-org/Pincer#52]
**Describe the bug**

Circular imports for `pincer.objects.interactions`

Error:
```

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/__init__.py", line 17, in <module>
    from pincer.client import Client, Bot
  File "/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/client.py", line 37, in <module>
    from pincer.objects.user import User
  File "/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/objects/__init__.py", line 41, in <module>
    from .interactions import Interaction, MessageInteraction
  File "/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/objects/interactions.py", line 33, in <module>
    from pincer.objects.message import Message
  File "/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/objects/message.py", line 36, in <module>
    from pincer.objects.interactions import MessageInteraction
ImportError: cannot import name 'MessageInteraction' from partially initialized module 'pincer.objects.interactions' (most likely due to a circular import) (/home/docs/checkouts/readthedocs.org/user_builds/pincer-test/checkouts/latest/pincer/objects/interactions.py)
```

**Comment by Arthurdw** [comment]
Issue has been resolved in [0b99915](https://github.com/Pincer-org/Pincer/commit/7948f8343881df209fc689675d876d9084308c32)

Thanks for reporting ♥
